name: Create Discussion
description: 'Creates a discussion if it does not exist'
inputs:
  title:
    required: true
    description: 'The title for the discussion'
  body:
    required: true
    description: 'The body for the discussion'

# Map the workflow outputs to job outputs
outputs:
  id:
    description: "The ID of the existing discussion"
    value: ${{ jobs.create-discussion.outputs.id }}
  number:
    description: "The public facing number of the existing discussion"
    value: ${{ jobs.create-discussion.outputs.number }}

runs:
  using: composite
  steps:
    - uses: octokit/graphql-action@v2.x
      id: create_discussion
      with:
        query: |
          mutation discussion($repoid:ID!,$categoryid:ID!,$body:String!,$title:String!) {
            createDiscussion(input: {repositoryId: $repoid, categoryId: $categoryid, body: $body, title: $title}) {
              discussion {
                id
                number
              }
            }
          }
        repoid: ${{ secrets.REPO_ID }}
        categoryid: ${{ secrets.CATEGORY_ID }}
        body: ${{ inputs.body }}
        title: ${{ inputs.title }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_ID: ${{ secrets.REPO_ID }}
        CATEGORY_ID: ${{ secrets.CATEGORY_ID }}

    - id: get_ids
      run: |
        cat <<EOF > temp.json
          ${{ steps.create_discussion.outputs.data }}
        EOF
        DID=$(cat temp.json | jq -r .createDiscussion.discussion.id)
        DNO=$(cat temp.json | jq -r .createDiscussion.discussion.number)
        echo "::set-output name=id::$DID"
        echo "::set-output name=number::$DNO"
        echo "Created new discussion with ID: $DID, number #$DNO"
      shell: bash
