name: Post to Social Platforms
description: Posts to social platforms like Twitter
inputs:
  slug:
    required: true
    description: Internal ID
  title:
    required: true
    description: Title

runs:
  using: composite
  steps:
    # Publish tweet to Twitter about new post
    - uses: ethomson/send-tweet-action@v1
      with:
        status: Check out “${{ inputs.title }}”! https://nevulo.xyz/blog/${{ inputs.slug }}
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    
