name: Cross-post to External Platforms

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      slug:
        required: true
        type: string
      title:
        required: true
        type: string
      body:
        required: true
        type: string
      description:
        required: true
        type: string
      image:
        required: true
        type: string
      original_url:
        required: true
        type: string
      tags:
        required: true
        type: string

    # Map the workflow outputs to job outputs
    outputs:
      medium_id:
        value: ${{ jobs.cross-post.outputs.medium_id }}
      medium_url:
        value: ${{ jobs.cross-post.outputs.medium_url }}
      devto_id:
        value: ${{ jobs.cross-post.outputs.devto_id }}
      devto_url:
        value: ${{ jobs.cross-post.outputs.devto_url }}
      hashnode_id:
        value: ${{ jobs.cross-post.outputs.hashnode_id }}
      hashnode_url:
        value: ${{ jobs.cross-post.outputs.hashnode_url }}

cross-post:
  outputs:
    medium_id: ${{ steps.medium.outputs.id }}
    medium_url: ${{ steps.medium.outputs.url }}
    devto_id: ${{ steps.devto.outputs.id }}
    devto_url: ${{ steps.devto.outputs.url }}
    hashnode_id: ${{ steps.hashnode.outputs.id }}
    hashnode_url: ${{ steps.hashnode.outputs.url }}
  name: Cross-post to Other Platforms
  runs-on: ubuntu-latest
  steps:
    - name: Publish to Hashnode
      uses: Nevvulo/hashnode-publisher@main
      id: hashnode
      with:
        api_key: ${{ secrets.HASHNODE_TOKEN }}
        publication_id: 6207ce33d59187113c4c098a
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        main_image: ${{ inputs.image }}
        original_url: ${{ inputs.original_url }}

    - name: Publish to Dev.to
      uses: Nevvulo/dev-to-publisher@main
      id: devto
      with:
        api_key: ${{ secrets.DEVTO_TOKEN }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        body: ${{ inputs.body }}
        main_image: ${{ inputs.image }}
        original_url: ${{ inputs.original_url }}
        tags: ${{ inputs.tags }}

    # TODO: not working?
    - name: Publish to Medium
      uses: infraway/medium-post-markdown@v1.6.0
      id: medium
      with:
        access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
        markdown_file: ${{ inputs.file }}
        base_url: https://nevulo.xyz
        post_url: https://nevulo.xyz/blog

    # Publish tweet to Twitter about new post
    - uses: ethomson/send-tweet-action@v1
      with:
        status: Check out “${{ inputs.title }}”! https://nevulo.xyz/blog/${{ inputs.slug }}
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
