name: Cross-post to External Platforms
description: Posts to external platforms like dev.to, Hashnode
inputs:
  file:
    required: true
    description: Filename
  slug:
    required: true
    description: Internal ID
  title:
    required: true
    description: Title
  devto_body:
    required: true
    description: Body for dev.to Post
  devto_token:
    required: true
    description: Token for dev.to post
  hashnode_body:
    required: true
    description: Body for Hashnode post
  hashnode_token:
    required: true
    description: Token for Hashnode post
  medium_body:
    required: true
    description: Body for Medium post
  medium_token:
    required: true
    description: Token for Medium post
  body:
    required: true
    description: Body for post
  description:
    required: true
    description: Description
  image:
    required: true
    description: Featured image
  original_url:
    required: true
    description: Canonical URL
  tags:
    required: true
    description: Tags for post

# Map the workflow outputs to job outputs
outputs:
  medium_id:
    description: Medium ID
    value: ${{ steps.medium.outputs.id }}
  medium_url:
    description: Medium URL
    value: ${{ steps.medium.outputs.url }}
  devto_id:
    description: dev.to ID
    value: ${{ steps.devto.outputs.id }}
  devto_url:
    description: dev.to ID
    value: ${{ steps.devto.outputs.url }}
  hashnode_id:
    description: Hashnode ID
    value: ${{ steps.hashnode.outputs.id }}
  hashnode_url:
    description: Hashnode ID
    value: ${{ steps.hashnode.outputs.url }}

runs:
  using: composite
  steps:
    - name: Publish to Hashnode
      uses: Nevvulo/hashnode-publisher@main
      id: hashnode
      # TOOD: needs tags
      with:
        api_key: ${{ inputs.hashnode_token }}
        publication_id: 6207ce33d59187113c4c098a
        title: ${{ inputs.title }}
        body: ${{ inputs.hashnode_body }}
        main_image: https://raw.githubusercontent.com/Nevvulo/blog/main/posts/assets/${{ inputs.slug }}/${{ inputs.image }}
        original_url: ${{ inputs.original_url }}

    - name: Publish to Dev.to
      uses: Nevvulo/dev-to-publisher@main
      id: devto
      with:
        api_key: ${{ inputs.devto_token }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        body: ${{ inputs.devto_body }}
        main_image: https://raw.githubusercontent.com/Nevvulo/blog/main/posts/assets/${{ inputs.slug }}/${{ inputs.image }}
        original_url: ${{ inputs.original_url }}
        tags: ${{ inputs.tags }}

    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: ./medium.md
        contents: ${{ inputs.medium_body }}

    - name: Publish to Medium
      uses: infraway/medium-post-markdown@v1.6.0
      id: medium
      with:
        access_token: ${{ inputs.medium_token }}
        markdown_file: ./medium.md
        post_url: https://nevulo.xyz/blog

    
