name: Add Blog Post
on:
  push:
    branches:
      - "main"
    paths:
      - "posts/**"
jobs:
  get-properties:
    name: Get Metadata from Post
    outputs:
      json: ${{ steps.metadata.outputs.json }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.0.0
        with:
          files: posts

      # Gets the line number where "<!--[PROPERTIES]" appears, reads $file from
      # that line number and removes the first and last line from selection
      # (because we don't want the opening and closing HTML tag in our YAML)

      # If an error occurs retrieving the line number for the [PROPERTIES] tag
      # (ie. it doesn't exist) - the step fails. Otherwise, we write the
      # selection to post-properties.yml
      - name: Read Post Properties and Write to File
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file"
            export PROPERTIES=$(tail -n `grep -e "<\!--\[PROPERTIES\]" -n $file | awk -F ":" '{print "+"$1}'` $file | tail -n +2 | sed '$d' || exit 1)
            [ "$PROPERTIES" ] || (echo "Error occurred while processing blog properties for $file: ensure that the properties exist at the bottom of the blog file and are in the correct format." && exit 1)
            echo -e "$PROPERTIES" >> post-properties.yml
            echo $(cat post-properties.yml)
          done

      # Converts the post-properties.yml file created from the previous step
      # to JSON to be written into blogmap.json
      - name: Convert Post Properties to JSON
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "post-properties.yml"
          from: "yaml"
          to: "json"

      - name: Write JSON Properties to File
        run: |
          cat <<EOF > post-properties.json
          ${{ steps.yaml2json.outputs.data }}
          EOF

      - id: metadata
        run: echo "::set-output name=json::`cat post-properties.json`"

  check-if-discussion-exists:
    name: Check If Discussion Already Exists
    outputs:
      exists: ${{ steps.metadata.outputs.exists }}
      slug: ${{ steps.metadata.outputs.slug }}
      title: ${{ steps.metadata.outputs.title }}
      did: ${{ steps.metadata.outputs.did }}
    runs-on: ubuntu-latest
    needs: get-properties
    steps:
      - uses: octokit/graphql-action@v2.x
        id: query_existing_discussion
        with:
          query: |
            query discussion($categoryid:ID!) {
              repository(owner: "Nevvulo", name: "blog") {
                discussions(categoryId: $categoryid, first: 100) {
                  nodes {
                    id
                    bodyText
                  }
                }
              }
            }
          categoryid: ${{ secrets.CATEGORY_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cat <<EOF > json.temp
          ${{ needs.get-properties.outputs.json }}
          EOF

      - id: metadata
        run: |
          export JSON=$(cat json.temp)
          echo $JSON

          cat <<EOF > response.json
          ${{ steps.query_existing_discussion.outputs.data }}
          EOF
          export RESPONSEJSON=$(cat response.json)

          export SLUG=`echo $(echo "$JSON" | jq -r '.[].slug')`
          export TITLE=`echo $(echo "$JSON" | jq -r '.[].title')`
          export LOCALID=`echo $(echo "$JSON" | jq -r '.[].discussionId')`
          export REMOTEID=`echo $(echo "$RESPONSEJSON" | jq -r '.repository.discussions.nodes | first(.[] | select(.bodyText == "'"$SLUG"'")) | .id')`
          echo "$LOCALID\n$REMOTEID"
          export DID=$([ "$LOCALID" != "null" ] && echo "$LOCALID" || echo "$REMOTEID")
          export EXISTS=$([ -n "$DID" ] && echo "true" || echo "false")
          echo "$SLUG\n$TITLE\n$DID\n$EXISTS"

          echo "::set-output name=slug::$SLUG"
          echo "::set-output name=title::$TITLE"
          echo "::set-output name=did::$DID"
          echo "::set-output name=exists::$EXISTS"

  create-discussion:
    name: Create Discussion
    if: ${{ needs.check-if-discussion-exists.outputs.exists != 'true' }}
    needs: [get-properties, check-if-discussion-exists]
    runs-on: ubuntu-latest
    outputs:
      discussion-id: ${{ steps.create_discussion.outputs.data }}
    steps:
      - uses: octokit/graphql-action@v2.x
        id: create_discussion
        with:
          query: |
            mutation discussion($repoid:ID!,$categoryid:ID!,$body:String!,$title:String!) {
              createDiscussion(input: {repositoryId: $repoid, categoryId: $categoryid, body: $body, title: $title}) {
                discussion {
                  id
                }
              }
            }
          repoid: ${{ secrets.REPO_ID }}
          categoryid: ${{ secrets.CATEGORY_ID }}
          body: ${{ needs.check-if-discussion-exists.outputs.slug }}
          title: ${{ needs.check-if-discussion-exists.outputs.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ID: ${{ secrets.REPO_ID }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}

      - run: |
          cat <<EOF > temp.json
            ${{ steps.create_discussion.outputs.data }}
          EOF
          DID=$(cat temp.json | jq -r .createDiscussion.discussion.id)
          echo "::set-output name=did::$DID"
          echo "Created new discussion with ID: $DID"

  create-post:
    needs: [get-properties, check-if-discussion-exists, create-discussion]
    if: always() && needs.get-properties.result == 'success'
    name: Append New Post to blogmap.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Write Properties to post-properties.json
        run: |
          cat <<EOF > post-properties.json
          ${{ needs.get-properties.outputs.json }}
          EOF

      - name: Get Discussion ID (new or existing)
        run: |
          NEWDID="${{ needs.create-discussion.outputs.did }}"
          EXISTINGDID="${{ needs.check-if-discussion-exists.outputs.did }}"
          export DID=$([ -n "$NEWDID" ] && echo "$NEWDID" || echo "$EXISTINGDID")
          echo "$NEWDID\n$EXISTINGDID\n$DID"
          if [[ -n "$DID" ]]; then
            echo Discussion ID could not be retrieved
            exit 1
          fi

      # Removes entries in blogmap that have the same slug as any incoming
      # posts and adds properties for new post
      - name: Write Post Properties to blogmap.json
        run: |
          echo $(jq --slurpfile post post-properties.json 'del(.[] | select(.slug == $post[][].slug)) | . += [$post[][] + { discussionId: ''"'"$DID"'"'' }] | sort_by(.createdAt) | reverse' blogmap.json -c) > blogmap.json

      # Validates that blogmap.json was written with the correct contents
      - name: Validate File Size
        run: |
          minimumsize=100
          actualsize=$(wc -c <blogmap.json)
          if [ $actualsize -ge $minimumsize ]; then
              echo blogmap.json size is over $minimumsize bytes
          else
              echo blogmap.json size is under $minimumsize bytes
              exit 1
          fi

      - name: Validate JSON Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./blogmap.json

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: "blogmap.json"
          default_author: github_actions
          message: "Update blogmap.json"
          signoff: true
