name: Add New Blog Post
on:
  push:
    branches:
      - "main"
    paths:
      - "posts/*"
jobs:
  create:
    # Only publish a new post if the commit message contains [P]
    if: ${{ contains(github.event.commits[0].message, '[P]') }}
    name: Create New Post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: |
            posts/*.md
            posts/*.mdx
          separator: " "

      # GET METADATA
      - name: Get Metadata for Post
        id: metadata
        uses: ./.github/workflows/internal/get-metadata
        with:
          # TODO: currently only supports one file
          file: ${{ steps.changed-files.outputs.added-files }}

      # CREATE DISCUSSION
      - name: Create Discussion
        id: discussion
        uses: ./.github/workflows/internal/create-discussion
        with:
          title: ${{ steps.metadata.outputs.title }}
          body: ${{ steps.metadata.outputs.slug }}

      - name: Transform Post Contents for Other Platforms
        id: transform
        uses: ./github/actions/transform-for-external
        with:
          contents: ${{ steps.metadata.outputs.body }}

      # CROSS-POST TO OTHER PLATFORMS
      - name: Cross-post to Other Platforms
        id: cross-post
        uses: ./.github/workflows/internal/cross-post-externally
        with:
          file: ${{ steps.changed-files.outputs.added-files }}
          slug: ${{ steps.metadata.outputs.slug }}
          title: ${{ steps.metadata.outputs.title }}
          body: ${{ steps.metadata.outputs.body }}
          medium_body: ${{ steps.transform.outputs.medium }}
          devto_body: ${{ steps.transform.outputs.devto }}
          hashnode_body: ${{ steps.transform.outputs.hashnode }}
          description: ${{ steps.metadata.outputs.description }}
          image: ${{ steps.metadata.outputs.image }}
          original_url: ${{ steps.metadata.outputs.original_url }}
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Read blogmap.json
        id: blogmap
        uses: juliangruber/read-file-action@v1
        with:
          path: ./blogmap.json

      # Uses IDs from discussion + cross-post steps
      - name: Update Post Properties
        id: post-properties
        uses: Nevvulo/upsert-json@1.0.0
        with:
          source_json: ${{ steps.metadata.outputs.json }}
          # TODO: it might be possible for strings to have "
          input_json: |
            {
              "discussionId": "${{ steps.discussion.outputs.id }}",
              "discussionNo": "${{ steps.discussion.outputs.number }}",
              "mediumId": "${{ steps.cross-post.outputs.medium_id }}",
              "mediumUrl": "${{ steps.cross-post.outputs.medium_url }}",
              "devToId": "${{ steps.cross-post.outputs.devto_id }}",
              "devToUrl": "${{ steps.cross-post.outputs.devto_url }}",
              "hashnodeId": "${{ steps.cross-post.outputs.hashnode_id }}",
              "hashnodeUrl": "${{ steps.cross-post.outputs.hashnode_url }}"
            }

      - name: Add Post to Blogmap
        uses: Nevvulo/upsert-json@1.0.0
        with: 
          source_json: ${{ steps.blogmap.outputs.content }}
          input_json: ${{ steps.post-properties.outputs.json }}
          filter_property: slug

      # Validates that blogmap.json was written with the correct contents
      - name: Validate File Size
        run: ./scripts/validate-file-size.sh blogmap.json

      - name: Validate JSON Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./blogmap.json

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "blogmap.json"
          default_author: github_actions
          message: "Update blogmap.json"
          signoff: true

      # If all is successful, post to social platforms
      - name: Post to Social Platforms
        id: social
        uses: ./.github/workflows/internal/social-post
        with:
          slug: ${{ steps.metadata.outputs.slug }}
          title: ${{ steps.metadata.outputs.title }}
