name: Add New Blog Post
on:
  push:
    branches:
      - "main"
    paths:
      - "posts/**"
jobs:
  create:
    # Only publish a new post if the commit message contains [P]
    if: ${{ contains(github.event.commits[0].message, '[P]') }}
    name: Create New Post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: posts
          separator: " "

      # GET METADATA
      - name: Get Metadata for Post
        id: metadata
        uses: ./.github/workflows/internal/get-metadata.yaml
        with:
          # TODO: currently only supports one file
          file: ${{ steps.changed-files.outputs.added-files }}

      # CROSS-POST TO OTHER PLATFORMS
      - name: Cross-post to Other Platforms
        id: cross-post
        uses: ./.github/workflows/internal/cross-post-externally.yaml
        with:
          file: ${{ steps.changed-files.outputs.added-files }}
          slug: ${{ steps.metadata.outputs.slug }}
          title: ${{ steps.metadata.outputs.title }}
          body: ${{ steps.metadata.outputs.body }}
          description: ${{ steps.metadata.outputs.description }}
          image: ${{ steps.metadata.outputs.image }}
          original_url: ${{ steps.metadata.outputs.original_url }}
          tags: ${{ steps.metadata.outputs.tags }}

      # CREATE DISCUSSION
      - name: Create Discussion
        id: discussion
        uses: ./.github/workflows/internal/create-discussion.yaml
        with:
          title: ${{ steps.metadata.outputs.title }}
          body: ${{ steps.metadata.outputs.slug }}

      # Uses IDs from discussion + cross-post steps
      - name: Add Post to Blogmap
        run: ./scripts/create-post-in-blogmap.sh $(cat ./post-properties.json)
        env:
          DISCUSSION_ID: ${{ steps.discussion.outputs.id }}
          DISCUSSION_NO: ${{ steps.discussion.outputs.number }}
          MEDIUM_ID: ${{ steps.cross-post.outputs.medium_id }}
          MEDIUM_URL: ${{ steps.cross-post.outputs.medium_url }}
          DEVTO_ID: ${{ steps.cross-post.outputs.devto_id }}
          DEVTO_URL: ${{ steps.cross-post.outputs.devto_url }}
          HASHNODE_ID: ${{ steps.cross-post.outputs.hashnode_id }}
          HASHNODE_URL: ${{ steps.cross-post.outputs.hashnode_url }}

      # Validates that blogmap.json was written with the correct contents
      - name: Validate File Size
        run: ./scripts/validate-file-size.sh blogmap.json

      - name: Validate JSON Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./blogmap.json

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "blogmap.json"
          default_author: github_actions
          message: "Update blogmap.json"
          signoff: true
