name: Update Existing Blog Post
on:
  push:
    branches:
      - "main"
    paths:
      - "posts/*"
jobs:
  setup:
    if: ${{ contains(github.event.commits[0].message, '[U]') }}
    name: Update Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v1.0.0
        with:
          files: |
            posts/*.md
            posts/*.mdx
          separator: " "

      # GET METADATA
      - name: Get Metadata for Post
        id: metadata
        uses: ./.github/workflows/internal/get-metadata
        with:
          # TODO: currently only supports one file
          file: ${{ steps.changed-files.outputs.added-files }}

      - name: Read blogmap.json
        id: blogmap
        uses: juliangruber/read-file-action@v1
        with:
          path: ./blogmap.json

      - name: Update Post Properties
        id: post-properties
        uses: Nevvulo/upsert-json@1.0.0
        with:
          source_json: ${{ steps.blogmap.outputs.content }}
          input_json: ${{ steps.metadata.outputs.json }}
          filter_property: slug

      # Validates that blogmap.json was written with the correct contents
      - name: Validate File Size
        run: ./scripts/validate-file-size.sh blogmap.json

      - name: Validate JSON Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./blogmap.json

      # TODO: does not support medium
      - name: Propagate Update to External Platforms
        id: cross-post
        if: ${{ steps.metadata.outputs.devtoid && steps.metadata.outputs.hashnodeid }}
        uses: ./.github/workflows/internal/update-cross-posts
        with:
          devto_id: ${{ steps.metadata.outputs.devtoid }}
          hashnode_id: ${{ steps.metadata.outputs.hashnodeid }}
          file: ${{ steps.changed-files.outputs.added-files }}
          slug: ${{ steps.metadata.outputs.slug }}
          title: ${{ steps.metadata.outputs.title }}
          body: ${{ steps.metadata.outputs.body }}
          devto_body: ${{ steps.transform.outputs.devto }}
          hashnode_body: ${{ steps.transform.outputs.hashnode }}
          description: ${{ steps.metadata.outputs.description }}
          image: ${{ steps.metadata.outputs.image }}
          original_url: ${{ steps.metadata.outputs.original_url }}
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "blogmap.json"
          default_author: github_actions
          message: "Update blogmap.json"
          signoff: true
