name: Update Existing Blog Post
on:
  push:
    branches:
      - "main"
    paths:
      - "posts/**"
jobs:
  setup:
    name: Update Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.0.0
        with:
          files: posts
          separator: " "

      - name: Read Post Properties and Write to File
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            ./scripts/extract-blog-properties.sh $file
          done

      # Converts the post-properties.yml file created from the previous step
      # to JSON to be written into blogmap.json
      - name: Convert Post Properties to JSON
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: post-properties.yml
          from: "yaml"
          to: "json"

      - name: Write JSON Properties to File
        run: |
          cat <<EOF > post-properties.json
          ${{ steps.yaml2json.outputs.data }}
          EOF

      - name: Update Post in blogmap.json
        run: ./scripts/upsert-post-in-blogmap.sh post-properties.json

      # Validates that blogmap.json was written with the correct contents
      - name: Validate File Size
        run: ./scripts/validate-file-size.sh blogmap.json

      - name: Validate JSON Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./blogmap.json

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "blogmap.json"
          default_author: github_actions
          message: "Update blogmap.json"
          signoff: true
